# Creates a Storage Account to utilize as a Terraform Back End. This must be destroyed manually in Azure when finished.

name: 'Terraform AKS'

on:
  workflow_dispatch:
  workflow_call:
  
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  TF_VAR_akc_ssh_key: ${{ secrets.TF_VAR_AKC_SSH_KEY }}

jobs:
  plan:
    strategy: 
      matrix: 
        env: [dev]
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    
    defaults:
          run:
            shell: bash
            working-directory: manifests/aks/
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with: 
            repository: brandencward/terraform-azure-modules
            
        - name: Terraform Plan
          run: |           
            terraform init
            terraform plan -input=false -var-file=../../env/${{ matrix.env  }}.tfvars -out tfplan
        
        - name: Terraform Apply
          run: |
            terraform apply -input=false "tfplan" 
